import { Head } from '@inertiajs/react';
import { useState } from 'react';
import OwnerShell from '../../Components/OwnerShell';

const money = (v) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(v);
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => { const d = new Date(); d.setDate(1); return d.toISOString().slice(0, 10); };

export default function Reports({ orders = [], meta = {}, filters = {} }) {
    const [from, setFrom] = useState(filters.from ?? monthStart()); const [to, setTo] = useState(filters.to ?? today()); const [status, setStatus] = useState(filters.status ?? 'paid'); const [rows, setRows] = useState(orders); const [summary, setSummary] = useState(meta); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
    async function load() { setLoading(true); setError(''); const response = await fetch(`/owner/reports?from=${from}&to=${to}&status=${status}`, { headers: { Accept: 'application/json' } }); setLoading(false); if (!response.ok) { setError('Gagal memuat laporan.'); return; } const body = await response.json(); setRows(body.data); setSummary(body.meta); }
    const csvUrl = `/owner/reports/csv?from=${from}&to=${to}&status=${status}`;
    return <><Head title="Laporan" /><OwnerShell title="Laporan transaksi" description="Baca performa penjualan, metode pembayaran, dan riwayat order secara terukur.">
        <section aria-label="Filter laporan" className="cafe-surface mb-6 p-5 sm:p-6"><div className="mb-5 flex items-start justify-between gap-3"><div><p className="cafe-kicker">Filter data</p><p className="mt-2 text-sm text-muted">Pilih rentang dan status transaksi.</p></div><span className="hidden rounded-full bg-cream px-3 py-1 text-xs font-semibold text-muted sm:block">CSV / PDF tersedia</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="block text-sm font-semibold">Dari<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="mt-1 block min-h-11 w-full rounded-xl border border-line bg-cream/40 px-3" /></label><label className="block text-sm font-semibold">Sampai<input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="mt-1 block min-h-11 w-full rounded-xl border border-line bg-cream/40 px-3" /></label><label className="block text-sm font-semibold">Status<select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-1 block min-h-11 w-full rounded-xl border border-line bg-cream/40 px-3"><option value="paid">Paid</option><option value="expired">Expired</option></select></label><button onClick={load} disabled={loading} className="min-h-11 self-end rounded-xl bg-espresso px-5 font-bold text-white hover:bg-terracotta disabled:opacity-50">{loading ? 'Memuat...' : 'Tampilkan'}</button><div className="flex gap-2 sm:col-span-2 lg:col-span-1"><a href={csvUrl} download className="flex min-h-11 flex-1 items-center justify-center rounded-xl border border-line px-3 text-xs font-bold hover:border-terracotta hover:text-terracotta">Unduh CSV</a><a href={`/owner/reports/pdf?from=${from}&to=${to}&status=${status}`} download className="flex min-h-11 flex-1 items-center justify-center rounded-xl border border-line px-3 text-xs font-bold hover:border-terracotta hover:text-terracotta">Unduh PDF</a></div></div></section>
        {error && <p role="alert" className="mb-4 rounded-2xl border border-danger/20 bg-red-50 p-4 text-sm font-semibold text-danger">{error}</p>}
        {summary.total_orders !== undefined && <div className="mb-5 grid gap-4 sm:grid-cols-3"><article className="cafe-stat bg-espresso text-white"><p className="text-xs text-cream/70">Total order</p><strong className="mt-1 block font-display text-2xl">{summary.total_orders}</strong></article><article className="cafe-stat border border-line bg-white"><p className="text-xs text-muted">Total revenue</p><strong className="mt-1 block font-display text-2xl text-espresso">{money(summary.total_revenue)}</strong></article><article className="cafe-stat border border-line bg-white"><p className="text-xs text-muted">Tunai / QRIS</p><strong className="mt-1 block text-sm text-espresso">{money(summary.cash_total)} · {money(summary.qris_total)}</strong></article></div>}
        <div className="cafe-surface overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="border-b border-line bg-cream/60"><tr>{['Nomor', 'Meja', 'Total', 'Metode', 'Waktu'].map((h) => <th key={h} className="px-5 py-4 text-left font-semibold text-muted">{h}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={5} className="px-4 py-10 text-center text-muted">Tidak ada data pada rentang ini.</td></tr> : rows.map((o) => <tr key={o.id} className="border-b border-line last:border-0 hover:bg-cream/40"><td className="px-5 py-4 font-mono text-xs">{o.number}</td><td className="px-5 py-4">{o.table?.name ?? '-'}</td><td className="px-5 py-4 font-semibold">{money(o.total)}</td><td className="px-5 py-4">{o.payment?.method ?? '-'}</td><td className="px-5 py-4 text-muted">{o.payment?.paid_at ? new Date(o.payment.paid_at).toLocaleString('id-ID') : '-'}</td></tr>)}</tbody></table></div>
    </OwnerShell></>;
}
