import { chromium } from 'playwright';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage();
await page.goto('http://127.0.0.1:8000/login');
await page.waitForLoadState('networkidle');
await page.getByLabel('Email').fill('kasir@kedaisenja.test');
await page.getByLabel('Password').fill('change-this-local-password');
await page.getByRole('button', {name:'Masuk'}).click();
await page.waitForTimeout(1500);
console.log('url', page.url());
console.log((await page.locator('body').innerText()).slice(0,3000));
await browser.close();
