import { Head, useForm } from '@inertiajs/react';

export default function Login() {
    const form = useForm({ email: '', password: '' });
    function submit(event) { event.preventDefault(); form.post('/login'); }
    return <><Head title="Masuk" /><main className="grid min-h-screen bg-cream lg:grid-cols-[1.05fr_.95fr]">
        <section className="relative hidden overflow-hidden bg-espresso p-10 text-cream lg:flex lg:flex-col lg:justify-between lg:p-14"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-terracotta/35 blur-3xl" /><div className="absolute -bottom-32 -left-20 h-72 w-72 rounded-full border-[32px] border-terracotta/20" /><div className="relative"><p className="font-mono text-xs uppercase tracking-[.24em] text-terracotta-soft">Kedai Senja · POS</p><h1 className="mt-10 max-w-lg font-display text-6xl font-bold leading-[.98]">Ritme kedai, lebih tertata.</h1><p className="mt-7 max-w-md text-base leading-7 text-cream/65">Satu ruang kerja untuk meracik order, menjaga stok, dan membaca performa kedai.</p></div><div className="relative flex items-center gap-3 text-sm text-cream/45"><span className="h-px w-10 bg-terracotta" />Warm tools for busy coffee hours.</div></section>
        <section className="flex items-center justify-center p-5 sm:p-10"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><p className="font-mono text-xs uppercase tracking-[.2em] text-terracotta">Kedai Senja · POS</p><h1 className="mt-3 font-display text-4xl font-bold text-espresso">Masuk ke kedai</h1></div><div className="rounded-[2rem] border border-line bg-white p-6 shadow-[0_20px_60px_rgba(76,51,31,.12)] sm:p-9"><div className="mb-8"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-terracotta-soft font-display text-2xl font-bold text-espresso">K</span><p className="mt-6 text-sm font-semibold text-muted">Workspace kasir & owner</p><h2 className="mt-2 font-display text-3xl font-bold text-espresso">Selamat datang kembali</h2></div><form onSubmit={submit}><label className="block text-sm font-semibold">Email<input required type="email" value={form.data.email} onChange={event => form.setData('email', event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-line bg-cream/30 px-4 outline-none transition focus:border-terracotta focus:ring-2 focus:ring-terracotta/20" autoComplete="username" /></label><label className="mt-5 block text-sm font-semibold">Password<input required type="password" value={form.data.password} onChange={event => form.setData('password', event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-line bg-cream/30 px-4 outline-none transition focus:border-terracotta focus:ring-2 focus:ring-terracotta/20" autoComplete="current-password" /></label>{form.errors.email && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-danger">{form.errors.email}</p>}<button disabled={form.processing} className="mt-7 w-full rounded-xl bg-espresso px-4 py-3.5 font-bold text-white shadow-lg shadow-espresso/15 transition hover:bg-terracotta focus:outline-none focus:ring-2 focus:ring-terracotta disabled:cursor-wait disabled:opacity-60">{form.processing ? 'Memeriksa...' : 'Masuk ke workspace'}</button></form></div></div></section>
    </main></>;
}
